# Generated by Django 5.0.6 on 2024-12-09 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_by', models.IntegerField(null=True)),
                ('update_at', models.DateTimeField(null=True)),
                ('update_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'sa_state',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('create_by', models.IntegerField(null=True)),
                ('update_at', models.DateTimeField(null=True)),
                ('update_by', models.IntegerField(null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_panel.state')),
            ],
            options={
                'db_table': 'sa_city',
            },
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('city_name', 'state_id'), name='unique_city_name_state_id'),
        ),
    ]
