# Generated by Django 5.1.3 on 2024-12-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adserviceprovider',
            name='parent_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
