# Generated by Django 5.1.3 on 2024-12-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0002_adserviceprovider_parent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='about_our_focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_our_mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_our_vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
