# Generated by Django 5.1.3 on 2024-12-19 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0003_aboutus_about_our_focus_aboutus_about_our_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluserdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.portaluser'),
        ),
        migrations.AlterField(
            model_name='portaluserdetails',
            name='pu',
            field=models.IntegerField(null=True),
        ),
    ]
