# Generated by Django 5.1.3 on 2024-12-23 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0004_portaluserdetails_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluserdetails',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portaluserdetails',
            name='pu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_hub.portaluser'),
        ),
    ]
