# Generated by Django 5.1.3 on 2025-01-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0005_alter_portaluserdetails_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='is_default_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='pu_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVERSED', 'Reversed')], default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='portaluser',
            name='is_kyc_verify',
            field=models.BooleanField(default=False),
        ),
    ]
