# Generated by Django 5.1.3 on 2025-01-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0006_portaluser_is_default_change_portaluser_pu_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaluser',
            name='pu_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
