# Generated by Django 5.1.5 on 2025-01-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0007_portaluser_pu_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='adservice',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='credentials_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='sa_provided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adserviceprovider',
            name='service_nature',
            field=models.CharField(blank=True, choices=[('charges', 'Charges'), ('commission', 'Commission')], max_length=20, null=True),
        ),
    ]
