# Generated by Django 5.1.1 on 2025-01-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_hub', '0008_adservice_is_global_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluserdetails',
            name='pud_unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
